LancerJeu()
// let inputEcriture = document.getElementById("inputEcriture")
// console.log(inputEcriture)
// let buttonValidation = document.getElementById("btnValiderMot")
// console.log(buttonValidation)
// let zoneProposition = document.querySelector(".zoneProposition")
// console.log(zoneProposition)
// let zoneScore = document.querySelector(".zoneScore span")
// console.log(zoneScore)
// let buttonChoix = document.querySelectorAll(".optionSource input")
// console.log(buttonChoix)